#!/usr/bin/env bash

# Shared B570 policy runtime defaults. Source this file before invoking the
# patched sample_multi_transcode_b570 binary. These values match the 2026-06-02
# B570 v3 10-minute validation run.

mfx50_b570_export_policy_env() {
    export MFX50RT_SAMPLE_HYBRIDTSRQ="${MFX50RT_SAMPLE_HYBRIDTSRQ:-1}"
    export MFX50RT_SAMPLE_HYBRIDTSRQ_ROI_ONLY="${MFX50RT_SAMPLE_HYBRIDTSRQ_ROI_ONLY:-1}"
    export MFX50RT_SAMPLE_HYBRIDTSRQ_DISABLE_FRAME_QP="${MFX50RT_SAMPLE_HYBRIDTSRQ_DISABLE_FRAME_QP:-1}"
    export MFX50RT_SAMPLE_DAYNIGHT_ADAPTIVE_QP="${MFX50RT_SAMPLE_DAYNIGHT_ADAPTIVE_QP:-0}"
    export MFX50RT_SAMPLE_HYBRIDTSRQ_HEAVY_INTERVAL="${MFX50RT_SAMPLE_HYBRIDTSRQ_HEAVY_INTERVAL:-5}"
    export MFX50RT_SAMPLE_MBQP_REUSE_INTERVAL="${MFX50RT_SAMPLE_MBQP_REUSE_INTERVAL:-30}"
    export MFX50RT_SAMPLE_ROI_ANALYZE_INTERVAL="${MFX50RT_SAMPLE_ROI_ANALYZE_INTERVAL:-30}"
    export MFX50RT_SAMPLE_DISABLE_ROI_FROM_MBQP="${MFX50RT_SAMPLE_DISABLE_ROI_FROM_MBQP:-1}"
    export MFX50RT_SAMPLE_ROI_DELTA_QP="${MFX50RT_SAMPLE_ROI_DELTA_QP:--4}"
    export MFX50RT_SAMPLE_PLATE_ROI_DELTA_QP="${MFX50RT_SAMPLE_PLATE_ROI_DELTA_QP:--12}"
    export MFX50RT_SAMPLE_PLATE_ROI_MARGIN="${MFX50RT_SAMPLE_PLATE_ROI_MARGIN:-24}"
    export MFX50RT_SAMPLE_MBQP_SAFE_MAX="${MFX50RT_SAMPLE_MBQP_SAFE_MAX:-38}"
}
